Update Makefile
nspcc-dev/neofs-http-gw pull request #162
Opened 2022-06-07 17:16 UTC by alexvanin

- Add `docker/$(BINS)` target.
- Remove help target. Help target will always ignore variable targets, it is confusing.
- Remove imports target. Go fmt is enough.
- Define lint version

Close #159

2022-06-07 17:19 UTC, realloc approved these changes

2022-06-07 17:19 UTC, realloc commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
Why not `make docker/all` ?

2022-06-07 18:14 UTC, 532910 requested changes
`docker/` make target is not described in readme, is it?

2022-06-07 18:32 UTC, alexvanin commented
> `docker/` make target is not described in readme, is it?

`docker/$(BINS)` target is described on this example from README:
```
To build neofs-http-gw binary in clean docker environment, call `make docker/bin/neofs-http-gw`.
```

2022-06-07 18:33 UTC, alexvanin commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
Because `make all` and therefore `make docker/all` is kinda useless in the repository with single binary artifact, on my opinion.

2022-06-07 18:37 UTC, realloc commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
I agree, but the purpose of the unification is to have the same script/job/prcedure for all neofs-* repos. Also, that's a common practice to make `all` the first target building all the binaries.

2022-06-07 18:51 UTC, alexvanin commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
I like how it became unification of all `neofs-*` and not `neo*` repos. :wink: 

So what is a common set of targets, then? Original issue suggested
- `bin` to create binary files,
- `docker/bin` to create binary files in clean Docker environment.

However `neo-go` doesn't have those, `neofs-node` will not build binaries in these targets.

Can we agree on this set of targets, then?
- `all`
- `docker/all`
- `$(BINS)`
- `docker/$(BINS)`

2022-06-07 18:54 UTC, realloc commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
bin meant $(BINS) originally, hence your proposal is exactly what was expected.

For the neo* repos, we are working on this.

2022-06-07 19:07 UTC, alexvanin commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
Check https://github.com/nspcc-dev/neofs-http-gw/pull/162/commits/98b06b56d36e54740f393cd396feb7ed3ffcbb80

I didn't add `docker/%` target because it allows `docker/bin`, `docker/clean` and other confusing options. I would like to avoid them.

2022-06-09 14:12 UTC, KirillovDenis commented on README.md
> +environment, call `make docker/bin/neofs-http-gw`.
Can we add `docker/%` and add condition to know run or abort command. maybe we can use something like:
```
docker/%:
	$(eval TARGET := $(strip $(subst docker/,,$@)))
	$(if $(filter $(TARGET),all bin), \
		@echo "valid", \
	  	@echo "invalid target '$(TARGET)' to run in docker")
```

2022-06-10 13:28 UTC, alexvanin commented
Reworked a bit solution from https://github.com/nspcc-dev/neofs-http-gw/pull/162#discussion_r893557954 in https://github.com/nspcc-dev/neofs-http-gw/pull/162/commits/b7b37c3695735c2822e64a50109cd799b467d836

2022-06-14 06:57 UTC, KirillovDenis approved these changes

2022-06-14 19:23 UTC, masterSplinter01 approved these changes

2022-06-15 08:05 UTC, realloc approved these changes

2022-06-15 10:21 UTC, merged