[#67] Added streaming to download
nspcc-dev/neofs-http-gw pull request #72
Opened 2021-06-23 12:15 UTC by KirillovDenis

closes #67 

Signed-off-by: Denis Kirillov <denis@nspcc.ru>

2021-06-23 14:29 UTC, roman-khimov requested changes

2021-06-23 14:29 UTC, roman-khimov commented on downloader/download.go
> -	r.Response.Header.Set("Content-Length", strconv.FormatUint(obj.PayloadSize(), 10))
Why?

2021-06-23 14:29 UTC, roman-khimov commented on downloader/download.go
> +	return &detector{done: make(chan struct{}), data: make([]byte, 512)}
Magic constant.

2021-06-23 14:29 UTC, roman-khimov commented on downloader/download.go
> +		d.err = err
I don't see it being returned anywhere when `d.data` is to be read.

2021-06-23 14:29 UTC, roman-khimov commented on downloader/download.go
> +	return io.MultiReader(bytes.NewReader(d.data), d.Reader)
And I'm not sure it works for objects less than 512 bytes.

2021-06-23 14:29 UTC, roman-khimov commented on downloader/download.go
> +	<-d.done
If error happens in `Detect`, this will hang forever?

2021-06-23 14:33 UTC, KirillovDenis commented on downloader/download.go
> -	r.Response.Header.Set("Content-Length", strconv.FormatUint(obj.PayloadSize(), 10))
When `Content-Type` header is specified client has got error `net::ERR_INVALID_CHUNKED_ENCODING`.

2021-06-23 14:39 UTC, roman-khimov commented on downloader/download.go
> -	r.Response.Header.Set("Content-Length", strconv.FormatUint(obj.PayloadSize(), 10))
Ah. So streaming switches it to chunked encoding which is not really compatible with length specification. Interesting. We can do this only starting from some object size. And IIRC length still can be passed somehow, let me check it.

2021-06-23 14:39 UTC, KirillovDenis commented on downloader/download.go
> +	return io.MultiReader(bytes.NewReader(d.data), d.Reader)
I've tried. It works.

2021-06-23 15:15 UTC, roman-khimov commented on downloader/download.go
> -	r.Response.Header.Set("Content-Length", strconv.FormatUint(obj.PayloadSize(), 10))
`func (resp *Response) writeBodyStream(w *bufio.Writer, sendBody bool) (err error)` suggests that it shouldn't be doing chunked encoding with proper `Content-Length` set. So I'm not sure how we end up with chunks here.

2021-06-23 15:32 UTC, KirillovDenis commented on downloader/download.go
> -	r.Response.Header.Set("Content-Length", strconv.FormatUint(obj.PayloadSize(), 10))
I'll check it again. It seems I've made a mistake

2021-06-23 18:39 UTC, KirillovDenis commented on downloader/download.go
> +		d.err = err
It will be returned when we invoke `MultiReader` function.

2021-06-23 19:42 UTC, roman-khimov commented on downloader/download.go
> +		d.err = err
Hmm. `MultiReader` concatenates multiple reader, the first one is a `bytes.Reader` created from `d.data`, it won't return an error even though we clearly already have one. Then it'll move on to `d.Reader` which probably will return an error, but who knows will it really do that and will this error be the same as `d.err`. I'd expect error to be returned immediately with `d.data`. Or am I missing something?

2021-06-23 19:42 UTC, roman-khimov commented on downloader/download.go
> +			go func() {
Can we move `r.Response.SetBodyStream` out of `WithPayloadReaderHandler` to avoid this asynchronous code? `readDetector` will have proper `reader` inside already, so it shouldn't be a problem.

2021-06-23 19:42 UTC, roman-khimov commented on downloader/download.go
> +			r.Error("could read object", fasthttp.StatusBadRequest)
`could read`?

2021-06-24 09:12 UTC, roman-khimov reviewed
Looks good now, squash?

2021-06-24 10:28 UTC, roman-khimov approved these changes

2021-06-24 10:28 UTC, merged